### ISSUE TITLE
JDBC "use block update" still a supported connection property?  What does it actually do?

### ISSUE THREAD

**Issue by charles-slc** [IBM/JTOpen#217]
In the [7.4 docs](https://www.ibm.com/docs/en/i/7.4?topic=jdbc-toolbox-java-properties),  There is

> "use block update" - This property allows the toolbox JDBC driver to use a block update mode when updating blocks of data into the database. This is an optimized version of the batch update. Default - false

But it's not show in the [7.5 docs](https://www.ibm.com/docs/api/v1/content/ssw_ibm_i_75/rzahh/javadoc/com/ibm/as400/access/doc-files/JDBCProperties.html)

Looking at the code, it's seems to still be recognized, but a quick glance didn't show any real usage of it.

So first question, is it still a functional properties and if so, then what does it do?   I'm guessing it changes something about UPDATE via `AddBatch()`

**Comment by jeber-ibm** [comment]
The "use block update"  setting allows updates made using  PreparedStatement.addBatch() and PreparedStatement.executeBatch() to be sent in a single request to the server.  Otherwise, the JDBC driver sends each update as individual requests to the server. 

The setting is supported.   For the javadoc, its best to refer to the latest JTOpen documentation at https://javadoc.io/doc/net.sf.jt400/jt400/latest/index.html.
