### ISSUE TITLE
JDK 9+ version missing from Maven Central

### ISSUE THREAD

**Issue by Viserius** [IBM/JTOpen#74]
Previously, we had to use version 10.7 with maven's <classifier>jt400_jdk9</classifier>-tag since our application is built using Java 17.
However, this classifier seems to be missing from version 11.2.
Should this version still be created/pushed, or is there a reason that there is no longer a jdk 9+ version in maven for version 11.2?

**Comment by ThePrez** [comment]
Hi, @Viserius. 
Unfortunately, there were some process issues with the publish of 11.2. Unless you require any of the updates in 11.2, it is recommended that you use version 11.1 for now (or the base "jt400" package).

With version 20.x, the coordinates are named slightly differently (in particular, since Java 9 and 10 were feature releases, you may need the `java11` coordinate). If you feel comfortable, you can evaluate this change on the 20.0.0-alpha-2 release.
